function T04 = ee_pos(in1)
%EE_POS
%    T04 = EE_POS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    08-Dec-2022 00:42:22

Q1 = in1(1,:);
Q2 = in1(2,:);
Q3 = in1(3,:);
Q4 = in1(4,:);
mt1 = [cos(Q4).*(cos(Q1).*cos(Q2).*cos(Q3)+cos(Q1).*sin(Q2).*sin(Q3))-sin(Q1).*sin(Q4),cos(Q4).*(cos(Q2).*cos(Q3).*sin(Q1)+sin(Q1).*sin(Q2).*sin(Q3))+cos(Q1).*sin(Q4),-cos(Q4).*(cos(Q2).*sin(Q3)-cos(Q3).*sin(Q2)),0.0];
mt2 = [sin(Q4).*(cos(Q1).*cos(Q2).*cos(Q3)+cos(Q1).*sin(Q2).*sin(Q3)).*(-5.73576436351046e-1)-cos(Q4).*sin(Q1).*5.73576436351046e-1+cos(Q1).*cos(Q2).*sin(Q3).*8.191520442889918e-1-cos(Q1).*cos(Q3).*sin(Q2).*8.191520442889918e-1];
mt3 = [sin(Q4).*(cos(Q2).*cos(Q3).*sin(Q1)+sin(Q1).*sin(Q2).*sin(Q3)).*(-5.73576436351046e-1)+cos(Q1).*cos(Q4).*5.73576436351046e-1+cos(Q2).*sin(Q1).*sin(Q3).*8.191520442889918e-1-cos(Q3).*sin(Q1).*sin(Q2).*8.191520442889918e-1];
mt4 = [sin(Q4).*(cos(Q2).*sin(Q3)-cos(Q3).*sin(Q2)).*5.73576436351046e-1+cos(Q2).*cos(Q3).*8.191520442889918e-1+sin(Q2).*sin(Q3).*8.191520442889918e-1,0.0];
mt5 = [sin(Q4).*(cos(Q1).*cos(Q2).*cos(Q3)+cos(Q1).*sin(Q2).*sin(Q3)).*8.191520442889918e-1+cos(Q4).*sin(Q1).*8.191520442889918e-1+cos(Q1).*cos(Q2).*sin(Q3).*5.73576436351046e-1-cos(Q1).*cos(Q3).*sin(Q2).*5.73576436351046e-1];
mt6 = [sin(Q4).*(cos(Q2).*cos(Q3).*sin(Q1)+sin(Q1).*sin(Q2).*sin(Q3)).*8.191520442889918e-1-cos(Q1).*cos(Q4).*8.191520442889918e-1+cos(Q2).*sin(Q1).*sin(Q3).*5.73576436351046e-1-cos(Q3).*sin(Q1).*sin(Q2).*5.73576436351046e-1];
mt7 = [sin(Q4).*(cos(Q2).*sin(Q3)-cos(Q3).*sin(Q2)).*(-8.191520442889918e-1)+cos(Q2).*cos(Q3).*5.73576436351046e-1+sin(Q2).*sin(Q3).*5.73576436351046e-1,0.0];
mt8 = [sin(Q1).*9.8e-3+cos(Q1).*cos(Q2).*(4.1e+1./1.0e+2)-cos(Q1).*cos(Q2).*sin(Q3).*2.491822393260846e-1+cos(Q1).*cos(Q3).*sin(Q2).*2.491822393260846e-1];
mt9 = [cos(Q1).*(-9.8e-3)+cos(Q2).*sin(Q1).*(4.1e+1./1.0e+2)-cos(Q2).*sin(Q1).*sin(Q3).*2.491822393260846e-1+cos(Q3).*sin(Q1).*sin(Q2).*2.491822393260846e-1];
mt10 = [sin(Q2).*(4.1e+1./1.0e+2)-cos(Q2).*cos(Q3).*2.491822393260846e-1-sin(Q2).*sin(Q3).*2.491822393260846e-1+2.755e-1,1.0];
T04 = reshape([mt1,mt2,mt3,mt4,mt5,mt6,mt7,mt8,mt9,mt10],4,4);
