function jacob_jeedq = endeffec_jacobian(in1,in2)
%ENDEFFEC_JACOBIAN
%    JACOB_JEEDQ = ENDEFFEC_JACOBIAN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    08-Dec-2022 23:47:46

Q1 = in1(1,:);
Q2 = in1(2,:);
Q3 = in1(3,:);
dQ1 = in2(1,:);
dQ2 = in2(2,:);
dQ3 = in2(3,:);
et1 = dQ1.*(cos(Q1).*sin(Q2).*(-4.1e+1./1.0e+2)+cos(Q1).*cos(Q2).*cos(Q3).*2.491822393260846e-1+cos(Q1).*sin(Q2).*sin(Q3).*2.491822393260846e-1)+dQ3.*sin(Q1).*sin(Q2-Q3).*2.491822393260846e-1;
et2 = dQ2.*sin(Q1).*(cos(Q2).*9.232379236109517e+16+sin(Q2-Q3).*5.611085200881502e+16).*(-4.440892098500626e-18);
et3 = dQ1.*(cos(Q1).*9.8e-3-cos(Q2).*sin(Q1).*(4.1e+1./1.0e+2)+cos(Q2).*sin(Q1).*sin(Q3).*2.491822393260846e-1-cos(Q3).*sin(Q1).*sin(Q2).*2.491822393260846e-1)-dQ3.*cos(Q1).*cos(Q2-Q3).*2.491822393260846e-1;
et4 = (dQ2.*cos(Q1).*(cos(Q2-Q3).*5.611085200881502e+16-sin(Q2).*9.232379236109517e+16))./2.251799813685248e+17;
et5 = dQ1.*(sin(Q1).*9.8e-3+cos(Q1).*cos(Q2).*(4.1e+1./1.0e+2)-cos(Q1).*cos(Q2).*sin(Q3).*2.491822393260846e-1+cos(Q1).*cos(Q3).*sin(Q2).*2.491822393260846e-1)-dQ3.*cos(Q2-Q3).*sin(Q1).*2.491822393260846e-1;
et6 = (dQ2.*sin(Q1).*(cos(Q2-Q3).*5.611085200881502e+16-sin(Q2).*9.232379236109517e+16))./2.251799813685248e+17;
et7 = dQ1.*(sin(Q1).*sin(Q2).*(-4.1e+1./1.0e+2)+cos(Q2).*cos(Q3).*sin(Q1).*2.491822393260846e-1+sin(Q1).*sin(Q2).*sin(Q3).*2.491822393260846e-1)-dQ3.*cos(Q1).*sin(Q2-Q3).*2.491822393260846e-1;
et8 = (dQ2.*cos(Q1).*(cos(Q2).*9.232379236109517e+16+sin(Q2-Q3).*5.611085200881502e+16))./2.251799813685248e+17;
mt1 = [dQ3.*(dQ1.*(cos(Q2).*cos(Q3).*sin(Q1).*2.491822393260846e-1+sin(Q1).*sin(Q2).*sin(Q3).*2.491822393260846e-1)+dQ2.*cos(Q1).*sin(Q2-Q3).*2.491822393260846e-1-dQ3.*cos(Q1).*sin(Q2-Q3).*2.491822393260846e-1)-dQ1.*(et5+et6)-dQ2.*(et7+et8)];
mt2 = [-dQ3.*(dQ1.*(cos(Q1).*cos(Q2).*cos(Q3).*2.491822393260846e-1+cos(Q1).*sin(Q2).*sin(Q3).*2.491822393260846e-1)-dQ2.*sin(Q1).*sin(Q2-Q3).*2.491822393260846e-1+dQ3.*sin(Q1).*sin(Q2-Q3).*2.491822393260846e-1)+dQ2.*(et1+et2)+dQ1.*(et3+et4)];
mt3 = [dQ2.^2.*cos(Q2-Q3).*2.491822393260846e-1+dQ3.^2.*cos(Q2-Q3).*2.491822393260846e-1-dQ2.^2.*sin(Q2).*(4.1e+1./1.0e+2)-dQ2.*dQ3.*cos(Q2-Q3).*4.983644786521693e-1];
jacob_jeedq = [mt1;mt2;mt3];
