function jacob_jeedq = endeffect_jacobian(in1,in2)
%ENDEFFECT_JACOBIAN
%    JACOB_JEEDQ = ENDEFFECT_JACOBIAN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    12-Dec-2022 12:55:30

Q1 = in1(1,:);
Q2 = in1(2,:);
Q3 = in1(3,:);
Q4 = in1(4,:);
dQ1 = in2(1,:);
dQ2 = in2(2,:);
dQ3 = in2(3,:);
dQ4 = in2(4,:);
et1 = dQ2.^2.*cos(Q2-Q3).*2.972275704841991e-1+dQ3.^2.*cos(Q2-Q3).*2.972275704841991e-1-dQ2.^2.*sin(Q2).*(4.1e+1./1.0e+2);
et2 = dQ2.^2.*sin(Q4).*sin(Q2-Q3).*6.861584392672606e-2+dQ3.^2.*sin(Q4).*sin(Q2-Q3).*6.861584392672606e-2;
et3 = dQ4.^2.*sin(Q4).*sin(Q2-Q3).*6.861584392672606e-2-dQ2.*dQ3.*cos(Q2-Q3).*5.944551409683983e-1;
et4 = dQ2.*dQ4.*cos(Q4).*cos(Q2-Q3).*(-1.372316878534521e-1)+dQ3.*dQ4.*cos(Q4).*cos(Q2-Q3).*1.372316878534521e-1;
et5 = dQ2.*dQ3.*sin(Q4).*sin(Q2-Q3).*(-1.372316878534521e-1);
et6 = dQ1.^2.*cos(Q1).*9.8e-3-dQ1.^2.*cos(Q1).*cos(Q4).*6.861584392672606e-2-dQ4.^2.*cos(Q1).*cos(Q4).*6.861584392672606e-2-dQ1.^2.*cos(Q2).*sin(Q1).*(4.1e+1./1.0e+2)-dQ2.^2.*cos(Q2).*sin(Q1).*(4.1e+1./1.0e+2);
et7 = dQ1.^2.*cos(Q2).*sin(Q1).*sin(Q3).*2.972275704841991e-1-dQ1.^2.*cos(Q3).*sin(Q1).*sin(Q2).*2.972275704841991e-1;
et8 = dQ2.^2.*cos(Q2).*sin(Q1).*sin(Q3).*2.972275704841991e-1-dQ2.^2.*cos(Q3).*sin(Q1).*sin(Q2).*2.972275704841991e-1;
et9 = dQ3.^2.*cos(Q2).*sin(Q1).*sin(Q3).*2.972275704841991e-1-dQ3.^2.*cos(Q3).*sin(Q1).*sin(Q2).*2.972275704841991e-1-dQ1.*dQ2.*cos(Q1).*sin(Q2).*(4.1e+1./5.0e+1);
et10 = dQ1.*dQ4.*sin(Q1).*sin(Q4).*1.372316878534521e-1+dQ1.^2.*cos(Q2).*cos(Q3).*sin(Q1).*sin(Q4).*6.861584392672606e-2;
et11 = dQ2.^2.*cos(Q2).*cos(Q3).*sin(Q1).*sin(Q4).*6.861584392672606e-2+dQ3.^2.*cos(Q2).*cos(Q3).*sin(Q1).*sin(Q4).*6.861584392672606e-2;
et12 = dQ4.^2.*cos(Q2).*cos(Q3).*sin(Q1).*sin(Q4).*6.861584392672606e-2+dQ1.^2.*sin(Q1).*sin(Q2).*sin(Q3).*sin(Q4).*6.861584392672606e-2;
et13 = dQ2.^2.*sin(Q1).*sin(Q2).*sin(Q3).*sin(Q4).*6.861584392672606e-2+dQ3.^2.*sin(Q1).*sin(Q2).*sin(Q3).*sin(Q4).*6.861584392672606e-2;
et14 = dQ4.^2.*sin(Q1).*sin(Q2).*sin(Q3).*sin(Q4).*6.861584392672606e-2+dQ1.*dQ2.*cos(Q1).*cos(Q2).*cos(Q3).*5.944551409683983e-1;
et15 = dQ1.*dQ3.*cos(Q1).*cos(Q2).*cos(Q3).*(-5.944551409683983e-1)+dQ1.*dQ2.*cos(Q1).*sin(Q2).*sin(Q3).*5.944551409683983e-1;
et16 = dQ1.*dQ3.*cos(Q1).*sin(Q2).*sin(Q3).*(-5.944551409683983e-1)-dQ2.*dQ3.*cos(Q2).*sin(Q1).*sin(Q3).*5.944551409683983e-1;
et17 = dQ2.*dQ3.*cos(Q3).*sin(Q1).*sin(Q2).*5.944551409683983e-1-dQ1.*dQ2.*cos(Q1).*cos(Q2).*sin(Q3).*sin(Q4).*1.372316878534521e-1;
et18 = dQ1.*dQ2.*cos(Q1).*cos(Q3).*sin(Q2).*sin(Q4).*1.372316878534521e-1+dQ1.*dQ3.*cos(Q1).*cos(Q2).*sin(Q3).*sin(Q4).*1.372316878534521e-1;
et19 = dQ1.*dQ3.*cos(Q1).*cos(Q3).*sin(Q2).*sin(Q4).*(-1.372316878534521e-1)-dQ1.*dQ4.*cos(Q1).*cos(Q4).*sin(Q2).*sin(Q3).*1.372316878534521e-1;
et20 = dQ2.*dQ3.*cos(Q2).*cos(Q3).*sin(Q1).*sin(Q4).*(-1.372316878534521e-1)-dQ2.*dQ4.*cos(Q2).*cos(Q4).*sin(Q1).*sin(Q3).*1.372316878534521e-1;
et21 = dQ2.*dQ4.*cos(Q3).*cos(Q4).*sin(Q1).*sin(Q2).*1.372316878534521e-1+dQ3.*dQ4.*cos(Q2).*cos(Q4).*sin(Q1).*sin(Q3).*1.372316878534521e-1;
et22 = dQ3.*dQ4.*cos(Q3).*cos(Q4).*sin(Q1).*sin(Q2).*(-1.372316878534521e-1)-dQ2.*dQ3.*sin(Q1).*sin(Q2).*sin(Q3).*sin(Q4).*1.372316878534521e-1;
et23 = dQ1.*dQ4.*cos(Q1).*cos(Q2).*cos(Q3).*cos(Q4).*(-1.372316878534521e-1);
et24 = dQ1.^2.*sin(Q1).*(-9.8e-3)-dQ1.^2.*cos(Q1).*cos(Q2).*(4.1e+1./1.0e+2)-dQ2.^2.*cos(Q1).*cos(Q2).*(4.1e+1./1.0e+2)+dQ1.^2.*cos(Q4).*sin(Q1).*6.861584392672606e-2+dQ4.^2.*cos(Q4).*sin(Q1).*6.861584392672606e-2;
et25 = dQ1.^2.*cos(Q1).*cos(Q2).*sin(Q3).*2.972275704841991e-1-dQ1.^2.*cos(Q1).*cos(Q3).*sin(Q2).*2.972275704841991e-1;
et26 = dQ2.^2.*cos(Q1).*cos(Q2).*sin(Q3).*2.972275704841991e-1-dQ2.^2.*cos(Q1).*cos(Q3).*sin(Q2).*2.972275704841991e-1;
et27 = dQ3.^2.*cos(Q1).*cos(Q2).*sin(Q3).*2.972275704841991e-1-dQ3.^2.*cos(Q1).*cos(Q3).*sin(Q2).*2.972275704841991e-1;
et28 = dQ1.*dQ4.*cos(Q1).*sin(Q4).*1.372316878534521e-1+dQ1.*dQ2.*sin(Q1).*sin(Q2).*(4.1e+1./5.0e+1)+dQ1.^2.*cos(Q1).*cos(Q2).*cos(Q3).*sin(Q4).*6.861584392672606e-2;
et29 = dQ2.^2.*cos(Q1).*cos(Q2).*cos(Q3).*sin(Q4).*6.861584392672606e-2+dQ3.^2.*cos(Q1).*cos(Q2).*cos(Q3).*sin(Q4).*6.861584392672606e-2;
et30 = dQ4.^2.*cos(Q1).*cos(Q2).*cos(Q3).*sin(Q4).*6.861584392672606e-2+dQ1.^2.*cos(Q1).*sin(Q2).*sin(Q3).*sin(Q4).*6.861584392672606e-2;
et31 = dQ2.^2.*cos(Q1).*sin(Q2).*sin(Q3).*sin(Q4).*6.861584392672606e-2+dQ3.^2.*cos(Q1).*sin(Q2).*sin(Q3).*sin(Q4).*6.861584392672606e-2;
et32 = dQ4.^2.*cos(Q1).*sin(Q2).*sin(Q3).*sin(Q4).*6.861584392672606e-2-dQ1.*dQ2.*cos(Q2).*cos(Q3).*sin(Q1).*5.944551409683983e-1;
et33 = dQ1.*dQ3.*cos(Q2).*cos(Q3).*sin(Q1).*5.944551409683983e-1-dQ2.*dQ3.*cos(Q1).*cos(Q2).*sin(Q3).*5.944551409683983e-1;
et34 = dQ2.*dQ3.*cos(Q1).*cos(Q3).*sin(Q2).*5.944551409683983e-1-dQ1.*dQ2.*sin(Q1).*sin(Q2).*sin(Q3).*5.944551409683983e-1;
et35 = dQ1.*dQ3.*sin(Q1).*sin(Q2).*sin(Q3).*5.944551409683983e-1+dQ1.*dQ4.*cos(Q2).*cos(Q3).*cos(Q4).*sin(Q1).*1.372316878534521e-1;
et36 = dQ2.*dQ3.*cos(Q1).*cos(Q2).*cos(Q3).*sin(Q4).*(-1.372316878534521e-1)-dQ2.*dQ4.*cos(Q1).*cos(Q2).*cos(Q4).*sin(Q3).*1.372316878534521e-1;
et37 = dQ2.*dQ4.*cos(Q1).*cos(Q3).*cos(Q4).*sin(Q2).*1.372316878534521e-1+dQ3.*dQ4.*cos(Q1).*cos(Q2).*cos(Q4).*sin(Q3).*1.372316878534521e-1;
et38 = dQ3.*dQ4.*cos(Q1).*cos(Q3).*cos(Q4).*sin(Q2).*(-1.372316878534521e-1)+dQ1.*dQ2.*cos(Q2).*sin(Q1).*sin(Q3).*sin(Q4).*1.372316878534521e-1;
et39 = dQ1.*dQ2.*cos(Q3).*sin(Q1).*sin(Q2).*sin(Q4).*(-1.372316878534521e-1)-dQ1.*dQ3.*cos(Q2).*sin(Q1).*sin(Q3).*sin(Q4).*1.372316878534521e-1;
et40 = dQ1.*dQ3.*cos(Q3).*sin(Q1).*sin(Q2).*sin(Q4).*1.372316878534521e-1+dQ1.*dQ4.*cos(Q4).*sin(Q1).*sin(Q2).*sin(Q3).*1.372316878534521e-1;
et41 = dQ2.*dQ3.*cos(Q1).*sin(Q2).*sin(Q3).*sin(Q4).*(-1.372316878534521e-1);
jacob_jeedq = [et24+et25+et26+et27+et28+et29+et30+et31+et32+et33+et34+et35+et36+et37+et38+et39+et40+et41;et6+et7+et8+et9+et10+et11+et12+et13+et14+et15+et16+et17+et18+et19+et20+et21+et22+et23;et1+et2+et3+et4+et5];
