function t5 = endeffector_cartesian(in1)
%ENDEFFECTOR_CARTESIAN
%    T5 = ENDEFFECTOR_CARTESIAN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    12-Dec-2022 12:37:46

Q1 = in1(1,:);
Q2 = in1(2,:);
Q3 = in1(3,:);
Q4 = in1(4,:);
et1 = sin(Q2).*(4.1e+1./1.0e+2)+sin(Q4).*(cos(Q2).*sin(Q3)-cos(Q3).*sin(Q2)).*6.861584392672606e-2-cos(Q2).*cos(Q3).*2.972275704841991e-1;
et2 = sin(Q2).*sin(Q3).*(-2.972275704841991e-1)+2.755e-1;
et3 = cos(Q1).*(-9.8e-3)-sin(Q4).*(cos(Q2).*cos(Q3).*sin(Q1)+sin(Q1).*sin(Q2).*sin(Q3)).*6.861584392672606e-2+cos(Q1).*cos(Q4).*6.861584392672606e-2+cos(Q2).*sin(Q1).*(4.1e+1./1.0e+2);
et4 = cos(Q2).*sin(Q1).*sin(Q3).*(-2.972275704841991e-1)+cos(Q3).*sin(Q1).*sin(Q2).*2.972275704841991e-1;
et5 = sin(Q1).*9.8e-3-sin(Q4).*(cos(Q1).*cos(Q2).*cos(Q3)+cos(Q1).*sin(Q2).*sin(Q3)).*6.861584392672606e-2+cos(Q1).*cos(Q2).*(4.1e+1./1.0e+2)-cos(Q4).*sin(Q1).*6.861584392672606e-2;
et6 = cos(Q1).*cos(Q2).*sin(Q3).*(-2.972275704841991e-1)+cos(Q1).*cos(Q3).*sin(Q2).*2.972275704841991e-1;
t5 = [et5+et6;et3+et4;et1+et2];
