function G = gravity_terms(in1)
%GRAVITY_TERMS
%    G = GRAVITY_TERMS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    05-Dec-2022 19:22:19

Q2 = in1(2,:);
Q3 = in1(3,:);
Q4 = in1(4,:);
et1 = sin(Q4).*(cos(Q2).*cos(Q3)+sin(Q2).*sin(Q3)).*1.076994286273892e-1+cos(Q2).*sin(Q3).*4.66528394631999e-1;
et2 = cos(Q3).*sin(Q2).*(-4.66528394631999e-1);
et3 = cos(Q2).*6.43536e-1-sin(Q4).*(cos(Q2).*cos(Q3)+sin(Q2).*sin(Q3)).*1.076994286273892e-1-cos(Q2).*sin(Q3).*4.66528394631999e-1;
et4 = cos(Q3).*sin(Q2).*4.66528394631999e-1;
G = [0.0;et3+et4;et1+et2;cos(Q4).*(cos(Q2).*sin(Q3)-cos(Q3).*sin(Q2)).*1.076994286273892e-1];
